site_name: GoLangGraph Studio
site_description: A fully functional React interface for debugging and testing GoLangGraph agents
site_author: GoLangGraph Team
site_url: https://piotrlaczkowski.github.io/GoLangGraph-Project/

repo_name: piotrlaczkowski/GoLangGraph-Project
repo_url: https://github.com/piotrlaczkowski/GoLangGraph-Project
edit_uri: edit/main/GoLangGraphStudio/docs/

copyright: Copyright &copy; 2024 GoLangGraph Studio

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - minify:
      minify_html: true
  - social:
      cards_layout_options:
        color: "#2196F3"

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: piotrlaczkowski
      repo: GoLangGraph-Project
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/piotrlaczkowski/GoLangGraph-Project
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/piotrlaczkowski/golanggraph-studio
  analytics:
    provider: google
    property: G-XXXXXXXXXX

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - Features:
    - Graph View: features/graph-view.md
    - Chat Mode: features/chat-mode.md
    - Debug View: features/debug-view.md
    - Agent Management: features/agent-management.md
  - User Guide:
    - Basic Usage: guide/basic-usage.md
    - Advanced Features: guide/advanced-features.md
    - Troubleshooting: guide/troubleshooting.md
  - Development:
    - Architecture: development/architecture.md
    - Contributing: development/contributing.md
    - API Integration: development/api-integration.md
    - Customization: development/customization.md
  - Reference:
    - Components: reference/components.md
    - Configuration: reference/configuration.md
    - API: reference/api.md
  - Examples:
    - Basic Setup: examples/basic-setup.md
    - Advanced Workflows: examples/advanced-workflows.md
  - About:
    - License: about/license.md
    - Changelog: about/changelog.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

docs_dir: docs
site_dir: site 