name: Build and Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'GoLangGraphStudio/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'GoLangGraphStudio/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./GoLangGraphStudio

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: GoLangGraphStudio/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test -- --coverage --watchAll=false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: GoLangGraphStudio/build
          retention-days: 7 