name: Build and Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'GoLangGraphStudio/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'GoLangGraphStudio/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./GoLangGraphStudio

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ./GoLangGraphStudio/node_modules
          key: ${{ runner.os }}-node-18-${{ hashFiles('GoLangGraphStudio/package-lock.json', 'GoLangGraphStudio/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-18-
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm test -- --coverage --watchAll=false || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: GoLangGraphStudio/build
          retention-days: 7 